### ISSUE TITLE
Spectator Mode not working

### ISSUE THREAD

**Issue by Wxrlds** [Wxrlds/Technocratica#1]
Spectator mode isn't working
[AvaritiaTweaks#4](https://github.com/JackyyTV/AvaritiaTweaks/issues/4)

**Comment by billyty08** [comment]
The only workaround I found is placing the infinity armor on and pressing the keybind for noclip to toggle it.

**Comment by Wxrlds** [comment]
Fixed thanks to the fork [Avaritia's Complement](https://minecraft.curseforge.com/projects/avaritia-complement)
