### ISSUE TITLE
Black Iron recipe help (Large Plates)

### ISSUE THREAD

**Issue by firestrongarch** [Wxrlds/Technocratica#10]
Unable to synthesize by Endless workbench
Change the secondary synthesis table to the ultimate synthesis table.Please！I neen play the game。

**Comment by Wxrlds** [comment]
Can you give me more information?
I'm unable to find an Endless Workbench.
What mod is it from? What exactly do you want to do?

**Comment by firestrongarch** [comment]
> Can you give me more information?
> I'm unable to find an Endless Workbench.
> What mod is it from? What exactly do you want to do?

this is my fault.
I can't speak English.
I can give you some picture.

![image](https://user-images.githubusercontent.com/65007434/81387021-91eb2100-9148-11ea-8dda-067b05a1c141.png)
![image](https://user-images.githubusercontent.com/65007434/81387167-da0a4380-9148-11ea-814e-fb4eaac4c689.png)

unable to synthesize this item in survival mode and all the equipment that need the black iron ingot at this stage.

**Comment by firestrongarch** [comment]
I need these item before this stage of Signalum cell Frame.
![批注 2020-05-08 164554](https://user-images.githubusercontent.com/65007434/81389340-40449580-914c-11ea-9aec-b0d176fec37c.png)
@Wxrlds

**Comment by Wxrlds** [comment]
I've added two Black Iron recipes. One in the Empowerer from Actually Additions and one in the Combination Crafting from Extended Crafting. To start, you have to use the Empowerer.

**Comment by firestrongarch** [comment]
Actually Additions need Void Large Plate.&nbsp;&nbsp;Combination Crafting need&nbsp;Black Iron.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wxrlds"<notifications@github.com&gt;; 
发送时间: 2020年5月8日(星期五) 晚上6:25
收件人: "Wxrlds/Technocratica"<Technocratica@noreply.github.com&gt;; 
抄送: "context"<chzufuyi@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Wxrlds/Technocratica] Element energy unit (#10)





 
I've added two Black Iron recipes. One in the Empowerer from Actually Additions and one in the Combination Crafting from Extended Crafting

**Comment by Wxrlds** [comment]
The Large Plates can be crafted in the Part Builder from Tinkers Construct

**Comment by firestrongarch** [comment]
I know your tinking,but this is a bug.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wxrlds"<notifications@github.com&gt;; 
发送时间: 2020年5月8日(星期五) 晚上6:50
收件人: "Wxrlds/Technocratica"<Technocratica@noreply.github.com&gt;; 
抄送: "context"<chzufuyi@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Wxrlds/Technocratica] Element energy unit (#10)





 
The Large Plates can be crafted in the Part Builder from Tinkers Construct

**Comment by Wxrlds** [comment]
Everything works as intended. I'm able to craft the Void Large Plate and Black Quartz Large Plate.
![grafik](https://user-images.githubusercontent.com/42120270/81401134-f39e9180-912e-11ea-8e5d-99c3c3d9c517.png)

**Comment by firestrongarch** [comment]
I understand.
thank you very munch.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wxrlds"<notifications@github.com&gt;; 
发送时间: 2020年5月8日(星期五) 晚上7:22
收件人: "Wxrlds/Technocratica"<Technocratica@noreply.github.com&gt;; 
抄送: "context"<chzufuyi@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Wxrlds/Technocratica] Black Iron recipe help (Large Plates) (#10)





 
Everything works as intended. I'm able to craft the Void Large Plate and Black Quartz Large Plate.
