### ISSUE TITLE
Unifying inconsistencies with Mekanism

### ISSUE THREAD

**Issue by NeverSalty** [Wxrlds/Technocratica#11]
Hey ich hab ein Problem gefunden im Technocratica Pack, wenn ich Erze pulveresiere mit dem Enrichmant Chamber und dann mit dem Smelter von Mekanism schmelze kommen IC2 Ingots raus und keine Thermal foundation Ingots

Hey I found a problem in the Technocratica Pack, when I powder ores with the Enrichmant Chamber and then melt with the Smelter from Mekanism, IC2 ingots come out and no thermal foundation ingots

**Comment by Wxrlds** [comment]
[Waiting for UniDict to fix Mekanism integration](https://github.com/WanionCane/UniDict/issues?q=is%3Aissue+is%3Aopen+mekanism)

**Comment by Wxrlds** [comment]
The next update attempts to fix this issue, if it still occurs either reopen this issue or open a new one giving examples of what items aren't unified.

**Comment by Wxrlds** [comment]
Check if this still occurs in [v2.1.03](https://www.curseforge.com/minecraft/modpacks/technocratica/files/3098738)
