### ISSUE TITLE
Any hope for NuclearCraft?

### ISSUE THREAD

**Issue by MOONLIT3** [Wxrlds/Technocratica#13]
Hello, I'm just wondering if there is any chance for NuclearCraft getting added to the pack? It's my favorite tech mod with amazing generation mechanics, so I'd love to see it implemented. I can gladly offer some help with coming up with quests and custom recipes, if necessary.

**Comment by Wxrlds** [comment]
Including NC would require the progression to be changed a lot and with the pack being almost ready to be marked as a released (not just beta) that's not gonna happen. But thanks for offering help.
