### ISSUE TITLE
Recipe issue

### ISSUE THREAD

**Issue by TheSnowyChickens** [Wxrlds/Technocratica#3]
Hi,
it is not possible to craft the macerator, because the quartz grindstone has no recipe.

Pack version: 2.0.15

![grafik](https://user-images.githubusercontent.com/29357962/65841852-f62e4280-e326-11e9-8f82-d1535f403984.png)
JEI shows me nothing.

**Comment by Wxrlds** [comment]
Fixed in the next update

**Comment by TheSnowyChickens** [comment]
Ty
