### ISSUE TITLE
Crash with Magic Bean

### ISSUE THREAD

**Issue by TheSnowyChickens** [Wxrlds/Technocratica#4]
Hi,
with your newest update from today (2.0.17), I get a crash, if I press the right mouse button at the magic bean from cyclic.
(I play on Forge version 14.23.5.2847 and I removed some client mods, like inv. tweaks and I don't have Opti installed)

![grafik](https://user-images.githubusercontent.com/29357962/66248629-74288a00-e729-11e9-84ed-0c5138295e4f.png)

Crash report:
https://paste.dimdev.org/ikefoniyow.mccrash

**Comment by Wxrlds** [comment]
I've disabled the Magic Bean now. It's Loot Table was empty anyways, this is probably the issue, not knowing what to do with an empty Loot Table.

**Comment by TheSnowyChickens** [comment]
Okay
