### ISSUE TITLE
/Dank/null Gravestone issues

### ISSUE THREAD

**Issue by ChrisCunningham3266** [Wxrlds/Technocratica#5]
Upon death the dank/null doesn't drop in graves. It goes flying in random directions sometimes 3 or 4 blocks away.

**Comment by Wxrlds** [comment]
Already reported
https://github.com/M4thG33k/TombManyGraves2/issues/53
https://github.com/p455w0rd/DankNull/issues/210

**Comment by Wxrlds** [comment]
Apparently this is fixed.
