### ISSUE TITLE
The Armor Bar is weird with hearts

### ISSUE THREAD

**Issue by TheSnowyChickens** [Wxrlds/Technocratica#6]
Hello,
with more and more hearts (BHC mod or Cyclic hearts), the armor bar is keep slipping up.
I don't want the bar in the middle of the screen, if I add more hearts. xD

Can you look in this "problem" ?

Ty :)

![grafik](https://user-images.githubusercontent.com/29357962/70296057-7a022080-17e9-11ea-886d-a2314b67d34f.png)

Version: 2.0.25

**Comment by Wxrlds** [comment]
This is an issue from [OverpoweredArmorBar](https://github.com/LocusWay/OverpoweredArmorBar/issues/13) but it seems like [OverloadedArmorBar](https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar) is a fork to fix that problem. I'll replace the mod in the next update (v2.0.26)

**Comment by TheSnowyChickens** [comment]
Great, ty. :)

**Comment by Wxrlds** [comment]
[Fixed in v2.0.26](https://www.curseforge.com/minecraft/modpacks/technocratica/files/2842154)
