### ISSUE TITLE
Inverted Bed bug & no JEI information for Iridium Ore

### ISSUE THREAD

**Issue by TheSnowyChickens** [Wxrlds/Technocratica#7]
Hi,
a simple bug, that you can't fix, but the bed from the "Inverted Bed" mod resets the days of the world.
(look behind the local difficulty)
Edit: sometimes, the Inverted Bed transform itself in a normal bed, after breaking.
(I placed the bed in the air (first with wood planks and after placing the bed, I destroyed the planks))

(after sleeping in the inverted bed)
![grafik](https://user-images.githubusercontent.com/29357962/71635369-44075f00-2c24-11ea-9bf8-a3efb2d08f7f.png)

(a backup world, before sleeping in the inverted bed)
![grafik](https://user-images.githubusercontent.com/29357962/71635386-6f8a4980-2c24-11ea-9755-28e22120a3b8.png)

And the Iridium Ore question: Does is also spawn in the mining world ? (JEI only shows the Overworld as spawnable dimension)

**Comment by Wxrlds** [comment]
I've reported the inverted bed bugs
https://github.com/Buuz135/Inverted-Bed/issues/2
https://github.com/Buuz135/Inverted-Bed/issues/3

Regarding the Iridium Ore, I've missed adding it to JEI for other dimensions, will be added in v2.0.30

**Comment by Wxrlds** [comment]
Fixed in [V2.0.32](
https://www.curseforge.com/minecraft/modpacks/technocratica/files/2858906)
